from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI()

# Enable CORS for frontend domain & local testing
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def home():
    return {"status": "online", "message": "API working"}

class HtaccessPayload(BaseModel):
    force_https: bool = False
    www_redirect: str = "none"
    enable_litespeed_cache: bool = False
    enable_cors: bool = False
    custom_redirects: list = []

@app.post("/generate-htaccess")
def generate_htaccess(payload: HtaccessPayload):
    rules = ["# Generated by ChiralGrid"]
    if payload.force_https:
        rules.append("RewriteEngine On\nRewriteCond %{HTTPS} off\nRewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]")
    if payload.enable_cors:
        rules.append('Header set Access-Control-Allow-Origin "*"')
    return {"htaccess_code": "\n\n".join(rules)}


