import os
from typing import List, Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(title="ChiralGrid Tools API", version="1.0.0")

# Enable CORS for WordPress frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def read_root():
    return {"status": "online", "service": "ChiralGrid API"}

# --- TOOL: Freelance Rate & Cost Estimator ---
class RatePayload(BaseModel):
    target_income: Optional[float] = 0.0
    hours_per_week: Optional[float] = 40.0
    vacation_weeks: Optional[float] = 2.0
    tax_rate: Optional[float] = 15.0
    rush_delivery: Optional[bool] = False

@app.post("/calculate-rate")
@app.post("/calculate-ai-cost")
@app.post("/estimate-project")
def calculate_rate(payload: RatePayload):
    working_weeks = max(1.0, 52.0 - payload.vacation_weeks)
    total_hours = working_weeks * payload.hours_per_week
    if total_hours <= 0:
        raise HTTPException(status_code=400, detail="Working hours must be greater than zero.")

    tax_factor = max(0.01, 1.0 - (payload.tax_rate / 100.0))
    gross_needed = payload.target_income / tax_factor
    base_rate = gross_needed / total_hours

    if payload.rush_delivery:
        base_rate *= 1.30

    return {
        "hourly_rate": round(base_rate, 2),
        "total_billable_hours": round(total_hours, 1),
        "gross_income_needed": round(gross_needed, 2)
    }

# --- TOOL: Redirect Auditor ---
class AuditPayload(BaseModel):
    url: str

@app.post("/audit-redirects")
def audit_redirects(payload: AuditPayload):
    # Placeholder/existing logic for audit-redirects
    return {"url": payload.url, "status": "Audited", "redirects": []}

# --- TOOL: PDF To Images ---
class PdfPayload(BaseModel):
    file_data: Optional[str] = None

@app.post("/convert-pdf-to-images")
def convert_pdf_to_images(payload: PdfPayload):
    return {"status": "success", "message": "PDF conversion endpoint ready"}

# --- TOOL: Image Converter ---
class ImagePayload(BaseModel):
    image_data: Optional[str] = None
    target_format: Optional[str] = "png"

@app.post("/convert-image")
def convert_image(payload: ImagePayload):
    return {"status": "success", "format": payload.target_format}

# --- TOOL: Images To PDF ---
class ImagesToPdfPayload(BaseModel):
    images: Optional[List[str]] = []

@app.post("/convert-images-to-pdf")
def convert_images_to_pdf(payload: ImagesToPdfPayload):
    return {"status": "success", "message": "Images to PDF conversion endpoint ready"}

# --- TOOL: .htaccess Generator ---
class HtaccessPayload(BaseModel):
    force_https: bool = False
    www_redirect: str = "none"
    enable_litespeed_cache: bool = False
    enable_cors: bool = False
    custom_redirects: Optional[List[dict]] = []

@app.post("/generate-htaccess")
def generate_htaccess(payload: HtaccessPayload):
    rules = ["# Generated by ChiralGrid"]
    if payload.force_https:
        rules.append("RewriteEngine On\nRewriteCond %{HTTPS} off\nRewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]")
    if payload.www_redirect == "force_www":
        rules.append("RewriteEngine On\nRewriteCond %{HTTP_HOST} !^www\\. [NC]\nRewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]")
    elif payload.www_redirect == "remove_www":
        rules.append("RewriteEngine On\nRewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]\nRewriteRule ^(.*)$ https://%1/$1 [R=301,L]")
    if payload.enable_litespeed_cache:
        rules.append("<IfModule Litespeed>\nSetEnv LCACHE_BUF 1\n</IfModule>")
    if payload.enable_cors:
        rules.append('Header set Access-Control-Allow-Origin "*"')
    return {"htaccess_code": "\n\n".join(rules)}

# --- TOOL: Gemini AI Explanation Endpoint (Lazy Loaded) ---
class ExplainPayload(BaseModel):
    htaccess_code: str

@app.post("/api/v1/explain-htaccess")
async def explain_htaccess(payload: ExplainPayload):
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise HTTPException(
            status_code=500,
            detail="GEMINI_API_KEY environment variable is missing on Vercel."
        )

    if not payload.htaccess_code or not payload.htaccess_code.strip():
        raise HTTPException(status_code=400, detail="Please generate or paste .htaccess rules first.")

    try:
        from google import genai
        client = genai.Client(api_key=api_key)

        prompt = (
            "You are a web sysadmin. Explain these .htaccess rules in 2-3 plain English bullet points:\n\n"
            f"{payload.htaccess_code}"
        )
        response = client.models.generate_content(
            model="gemini-3.8-flash",
            contents=prompt
        )
        return {"explanation": response.text}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"AI Error: {str(e)}")


